[color]
background = '#111318'
foreground = '#acc7ff'
gradient = 1
gradient_color_1 = '#acc7ff'
gradient_color_2 = '#bec6dc'
gradient_color_3 = '#ddbce0'
gradient_color_4 = '#294677'
gradient_color_5 = '#3f4759'
horizontal_gradient = 1
horizontal_gradient_color_1 = '#44474e'
horizontal_gradient_color_2 = '#bec6dc'
horizontal_gradient_color_3 = '#ddbce0'
blend_direction = 'up'