general {
    lock_cmd = hyprlock
    before_sleep_cmd = hyprlock
}

listener {
    timeout = 60
    on-timeout = hyprlock
}

listener {
    timeout = 100
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}