cursor            #ffb878
cursor_text_color #4b2700

foreground            #efe0d5
background            #130d07
selection_foreground  #412c19
selection_background  #e2c0a5
url_color             #e2c0a5

#: black 000000 767676
color0  #19120c
color8  #3c332c
#: red cc0403 f2201f
color1  #41352d
color9  #9a806d
#: green 19cb00 23fd00
color2  #e2c0a5
color10 #ffdcc1
#: yellow cecb00 fffd00
color3  #c2cb98
color11 #dfe8b2
#: blue 0d73cc 1a8fff
color4  #6b3b03
color12 #ffb878
#: magenta cb1ed1 fd28ff
color5  #5a422d
color13 #e2c0a5
#: cyan 0dcdcd 14ffff
color6  #434a23
color14 #c2cb98
#: white dddddd ffffff
color7  #d6c3b6
color15 #efe0d5

mark1_foreground #2e1600
mark1_background #ffdcc1
mark2_foreground #291706
mark2_background #ffdcc1
mark3_foreground #181e00
mark3_background #dfe8b2

active_tab_foreground #4b2700
active_tab_background #ffb878
inactive_tab_foreground #ffdcc1
inactive_tab_background #6b3b03

active_border_color #ffb878
inactive_border_color #4b2700
# bell_border_color #ff5a00
