cursor            #acc7ff
cursor_text_color #0e2f60

foreground            #e2e2e9
background            #0c0e13
selection_foreground  #283041
selection_background  #bec6dc
url_color             #bec6dc

#: black 000000 767676
color0  #111318
color8  #33353a
#: red cc0403 f2201f
color1  #0b3b68
color9  #2389e9
#: green 19cb00 23fd00
color2  #bec6dc
color10 #dae2f9
#: yellow cecb00 fffd00
color3  #ddbce0
color11 #fbd7fc
#: blue 0d73cc 1a8fff
color4  #294677
color12 #acc7ff
#: magenta cb1ed1 fd28ff
color5  #3f4759
color13 #bec6dc
#: cyan 0dcdcd 14ffff
color6  #573e5b
color14 #ddbce0
#: white dddddd ffffff
color7  #c4c6d0
color15 #e2e2e9

mark1_foreground #001a40
mark1_background #d7e2ff
mark2_foreground #131c2c
mark2_background #dae2f9
mark3_foreground #29132e
mark3_background #fbd7fc

active_tab_foreground #0e2f60
active_tab_background #acc7ff
inactive_tab_foreground #d7e2ff
inactive_tab_background #294677

active_border_color #acc7ff
inactive_border_color #0e2f60
# bell_border_color #ff5a00
