cursor            #d6bbfb
cursor_text_color #3b255b

foreground            #e7e0e8
background            #100d12
selection_foreground  #352d40
selection_background  #cec2da
url_color             #cec2da

#: black 000000 767676
color0  #151218
color8  #37333a
#: red cc0403 f2201f
color1  #371f61
color9  #7d52c7
#: green 19cb00 23fd00
color2  #cec2da
color10 #ebddf7
#: yellow cecb00 fffd00
color3  #f2b7c2
color11 #ffd9df
#: blue 0d73cc 1a8fff
color4  #523c73
color12 #d6bbfb
#: magenta cb1ed1 fd28ff
color5  #4c4357
color13 #cec2da
#: cyan 0dcdcd 14ffff
color6  #653b44
color14 #f2b7c2
#: white dddddd ffffff
color7  #ccc4cf
color15 #e7e0e8

mark1_foreground #250e44
mark1_background #eddcff
mark2_foreground #20182a
mark2_background #ebddf7
mark3_foreground #321019
mark3_background #ffd9df

active_tab_foreground #3b255b
active_tab_background #d6bbfb
inactive_tab_foreground #eddcff
inactive_tab_background #523c73

active_border_color #d6bbfb
inactive_border_color #3b255b
# bell_border_color #ff5a00
